### ISSUE TITLE
Weird Message

### ISSUE THREAD

**Issue by kalvinator** [iridium-browser/iridium-browser#36] opened 2015-07-14 09:50 UTC
Why I got this message?

![printscreen2](https://cloud.githubusercontent.com/assets/13317162/8670555/18a7a868-29ec-11e5-9a62-390965a249a4.png)

**Comment by fancycode** [comment] 2015-07-14 09:54
We show the yellow bars for tracking requests that load something from Google. We are working to remove them through the various upcoming releases (the one you are seeing will be removed in the upcoming 43.8).

Duplicate of #10.

**Closed by fancycode** 2015-07-14 09:54 UTC

**Comment by kalvinator** [comment] 2015-07-14 10:11
When the new release will be available and do iridium will automatically update to the next version or do I need to install it manually? (download the msi executable and uninstall the previous version manually?)

**Comment by fancycode** [comment] 2015-07-14 10:42
Version 43.8 has been released today, so updated installers should be available shortly.

Unfortunately we don't support automatic updates on Windows yet, so you will have to install the new MSI manually (don't need to uninstall the previous version though).

**Comment by kalvinator** [comment] 2015-08-19 13:30
Hi,

Just saying that the message is still there when you go to the settings or in the other tools tabs.
