### ISSUE TITLE
Install on amd64 

### ISSUE THREAD

**Issue by Fredfirefox** [iridium-browser/iridium-browser#88] opened 2016-08-28 10:49 UTC
`W: The repository 'https://downloads.iridiumbrowser.de/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://downloads.iridiumbrowser.de/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
`

i use the install manual from https://iridiumbrowser.de/download.html

> wget -qO - https://downloads.iridiumbrowser.de/ubuntu/iridium-release-sign-01.pub|sudo apt-key add -
> sudo apt-add-repository 'https://downloads.iridiumbrowser.de/ubuntu main'
> sudo apt-get update
> sudo apt-get install iridium-browser

**Comment by EnMod** [comment] 2016-09-07 01:35
I can confirm, no new release here either.  Currently on Xubuntu Xenial.

**Comment by rafaelrpinto** [comment] 2016-09-29 23:24
I'm using Iridium on Xenial. 

The workaround is to change the repo from xenial to vivid:

`sudo nano /etc/apt/sources.list`

Replace:
`deb https://downloads.iridiumbrowser.de/ubuntu xenial main`
For:
`deb https://downloads.iridiumbrowser.de/ubuntu vivid main`

**Comment by jlacroix82** [comment] 2016-10-04 20:23
From looking at the contents of the Apt repositories, none of the packages have been updated since 2015. This means that by using this repository, we're not taking advantage of any security updates since then. Is this project dead?!

**Comment by EnMod** [comment] 2016-10-06 19:54
Oh man...that's discouraging.

**Comment by souldanger** [comment] 2016-10-07 07:51
our development team is working on a new release - please standby.

**Comment by jlacroix82** [comment] 2016-10-07 14:52
I'm glad that you guys are working on a new release. However, that alone doesn't build my confidence. Are releases going to be more consistent? A release once a year or so is potentially dangerous to users. We can't underestimate the importance of our browsers and security. It's important that a user's browser is up to date to protect against the latest CVE's. Once this new release that you're working on is out, can we expect more consistent updates? I understand that a developer's time is limited, but a browser that doesn't receive regular updates should be marked as "beta" to not give user's the false impression that they can expect the latest security updates in a timely fashion. I wish this project much success, but not having an update in the repositories for the greater part of a year, as well as not even supporting the most critical version of Ubuntu six months after it was released, does very little to make me feel comfortable using this browser. I hope to see this project succeed and go in a better direction.

**Comment by souldanger** [comment] 2017-01-04 18:35
Hi guys
the new Linux releases are finally out, please check [https://iridiumbrowser.de/download.html](https://iridiumbrowser.de/download.html)

**Closed by souldanger** 2017-01-04 18:35 UTC
Labels: linux
